import { $ } from "../core/dom.js";
import { saveNavigationState } from "../core/navigationPersistence.js";
import { state } from "../core/state.js";
import { updateModuleTabs } from "./moduleTabs.js";
import { setActiveGroup, setActiveTool } from "./toolSwitcher.js?v=20260811-highlighted-active-1";

export function renderVisibility() {
  const hasItems = state.negociadores.length > 0;
  const isMonitoramento = ["overview", "negociadores", "carteiras", "negociador", "monitorPlanilha", "monitorFechamento"].includes(state.mode);
  const isParecer = state.mode === "parecer";
  const isProtocolo = state.mode === "protocolo";
  const isColchao = state.mode === "colchao";
  const pageTitleIcon = $("#pageTitleIcon");
  if (pageTitleIcon) pageTitleIcon.src = moduleIcon(state.mode);
  const isAnalysis = state.mode === "analise";
  const isDefasagem = state.mode === "defasagem";
  const isConfiguracao = state.mode === "configuracao";
  const isDynamicTool = state.mode === "dynamicTool";
  const isBackoffice = state.mode === "mainhub" || isMonitoramento || isParecer || isProtocolo || isColchao || isDynamicTool;
  $("#emptyState").classList.toggle("hidden", hasItems || state.mode === "mainhub" || state.mode === "overview" || state.mode === "negociadores" || state.mode === "carteiras" || state.mode === "monitorPlanilha" || state.mode === "monitorFechamento" || isProtocolo || isColchao || isParecer || isAnalysis || isDefasagem || isConfiguracao || isDynamicTool);
  $("#mainHubContent").classList.toggle("hidden", state.mode !== "mainhub");
  $("#dynamicToolContent")?.classList.toggle("hidden", !isDynamicTool);
  $("#productionIntelligenceContent")?.classList.toggle("hidden", !isAnalysis);
  $("#defasagemContent")?.classList.toggle("hidden", !isDefasagem);
  $("#configContent")?.classList.toggle("hidden", !isConfiguracao);
  $("#content").classList.toggle("hidden", !hasItems || state.mode !== "negociador");
  $("#negociadoresContent").classList.toggle("hidden", state.mode !== "negociadores");
  $("#carteirasContent").classList.toggle("hidden", state.mode !== "carteiras");
  $("#monitorPlanilhaContent")?.classList.toggle("hidden", state.mode !== "monitorPlanilha");
  $("#monitorFechamentoContent")?.classList.toggle("hidden", state.mode !== "monitorFechamento");
  $("#overviewContent").classList.toggle("hidden", state.mode !== "overview");
  $("#parecerContent").classList.toggle("hidden", !isParecer);
  $("#protocoloContent").classList.toggle("hidden", !isProtocolo);
  $("#colchaoContent").classList.toggle("hidden", !isColchao);
  const hideModuleTabs = state.mode === "mainhub" || state.mode === "negociador" || isDynamicTool;
  document.querySelector(".module-tabs-row")?.classList.toggle("hidden", hideModuleTabs);
  document.querySelector(".topbar")?.classList.toggle("tabs-hidden", hideModuleTabs);
  $("#monitorNav").classList.toggle("hidden", !isMonitoramento);
  $("#parecerNav").classList.toggle("hidden", !isParecer);
  $("#protocoloNav").classList.toggle("hidden", !isProtocolo);
  $("#colchaoNav").classList.toggle("hidden", !isColchao);
  $("#configNav")?.classList.toggle("hidden", !isConfiguracao);
  $("#analiseNav")?.classList.toggle("hidden", !isAnalysis);
  $("#defasagemNav")?.classList.toggle("hidden", !isDefasagem);
  $("#toolDropdown")?.classList.toggle("hidden", !isBackoffice);
  $("#analiseToolDropdown")?.classList.toggle("hidden", !(isAnalysis || isDefasagem));
  $("#mainHubBtn").classList.toggle("active", state.mode === "mainhub");
  $("#overviewBtn").classList.toggle("active", state.mode === "overview");
  $("#negociadoresBtn").classList.toggle("active", state.mode === "negociadores");
  $("#carteirasBtn").classList.toggle("active", state.mode === "carteiras");
  $("#monitorPlanilhaBtn")?.classList.toggle("active", state.mode === "monitorPlanilha");
  $("#monitorFechamentoBtn")?.classList.toggle("active", state.mode === "monitorFechamento");
  $("#refreshBtn").classList.toggle("hidden", !isMonitoramento || state.mode === "monitorPlanilha");
  $("#parecerRefreshBtn")?.classList.toggle("hidden", !isParecer);
  $("#protocoloNewBtn")?.classList.toggle("hidden", !isProtocolo);
  $("#colchaoBackProfilesTopBtn")?.classList.toggle("hidden", !(isColchao && state.colchao.profile));
  if (isParecer) setActiveTool("parecer");
  else if (isProtocolo) setActiveTool("protocolo");
  else if (isColchao) setActiveTool("colchao");
  else if (state.mode === "analise") setActiveTool("analise");
  else if (state.mode === "defasagem") setActiveTool("defasagem");
  else if (state.mode === "configuracao") setActiveTool("configuracao");
  else if (isMonitoramento) setActiveTool("monitoramento");
  else setActiveTool("");
  if (state.mode === "analise" || state.mode === "defasagem") setActiveGroup("analise");
  else if (state.mode === "configuracao") setActiveGroup("configuracao");
  else setActiveGroup(state.activeGroup || "backoffice");
  updateModuleTabs();
  saveNavigationState();
}

function moduleIcon(mode) {
  if (mode === "parecer") return "/assets/icons/opinion-1.svg";
  if (mode === "protocolo") return "/assets/icons/protocol-template.svg";
  if (mode === "colchao") return "/assets/icons/mattress.svg";
  if (mode === "configuracao") return "/assets/icons/settings-settings.svg";
  if (mode === "mainhub" || mode === "analise") return "/assets/icons/dashboard-65.svg";
  if (mode === "defasagem") return "/assets/icons/monitoring-9.svg";
  return "/assets/icons/monitoring-9.svg";
}
