version: 2
updates:
  - package-ecosystem: pip
    directory: "/aplicacao-gerencial"
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: "/aplicacao-negocial"
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: "/aplicacao-gerencial"
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: "/aplicacao-negocial"
    schedule:
      interval: weekly
