"""Configuracao de ferramentas por carteira.

Revision ID: 20260727_0017
Revises: 20260727_0016
Create Date: 2026-07-27
"""
from __future__ import annotations

from alembic import op


revision = "20260727_0017"
down_revision = "20260727_0016"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS negocial.carteira_ferramentas_config (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            carteira TEXT NOT NULL,
            tool_key TEXT NOT NULL,
            enabled BOOLEAN NOT NULL DEFAULT TRUE,
            updated_by TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            CONSTRAINT uq_carteira_ferramenta_config UNIQUE (carteira, tool_key),
            CONSTRAINT ck_producao_sempre_ativa
                CHECK (tool_key <> 'producao' OR enabled = TRUE)
        )
        """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_carteira_ferramentas_carteira "
        "ON negocial.carteira_ferramentas_config(carteira)"
    )
    op.execute(
        """
        INSERT INTO negocial.schema_migrations_meta (revision, description)
        VALUES ('20260727_0017', 'Ativacao de ferramentas por carteira')
        ON CONFLICT (revision) DO NOTHING
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS negocial.carteira_ferramentas_config")
