"""Consolida no Alembic as estruturas antes mantidas pelo bootstrap.

Revision ID: 20260720_0011
Revises: 20260720_0010
Create Date: 2026-07-20
"""
from __future__ import annotations

from alembic import op


revision = "20260720_0011"
down_revision = "20260720_0010"
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS negocial.producao_gamma_gerencial (
            producao_id INTEGER PRIMARY KEY REFERENCES negocial.producao_registros(id) ON DELETE CASCADE,
            uf VARCHAR(2),
            data_ajuizamento DATE,
            updated_at TIMESTAMPTZ DEFAULT NOW()
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS negocial.producao_correcoes (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            producao_id INTEGER NOT NULL REFERENCES negocial.producao_registros(id) ON DELETE CASCADE,
            campo TEXT NOT NULL,
            valor_anterior TEXT,
            valor_novo TEXT,
            corrigido_por TEXT NOT NULL,
            motivo TEXT,
            criado_em TIMESTAMPTZ DEFAULT NOW(),
            visualizado_pelo_negociador BOOLEAN DEFAULT FALSE
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS negocial.carteira_schema_versions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            carteira_id INTEGER NOT NULL REFERENCES negocial.carteiras_negociais(id) ON DELETE CASCADE,
            version_number INTEGER NOT NULL,
            action VARCHAR(80) NOT NULL,
            schema_json JSONB NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            UNIQUE (carteira_id, version_number)
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS negocial.fechamento_mensal (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            carteira VARCHAR(80) NOT NULL,
            mes INTEGER NOT NULL CHECK (mes BETWEEN 1 AND 12),
            ano INTEGER NOT NULL CHECK (ano BETWEEN 2000 AND 2200),
            status VARCHAR(20) NOT NULL DEFAULT 'FECHADO',
            closed_by VARCHAR(80) NOT NULL,
            closed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
            UNIQUE (carteira, mes, ano)
        )
        """
    )

    op.execute("CREATE INDEX IF NOT EXISTS ix_negocial_correcoes_producao_date ON negocial.producao_correcoes(producao_id, criado_em DESC)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_negocial_correcoes_unread ON negocial.producao_correcoes(visualizado_pelo_negociador, producao_id) WHERE visualizado_pelo_negociador = FALSE")
    op.execute("CREATE INDEX IF NOT EXISTS ix_negocial_schema_versions_wallet_date ON negocial.carteira_schema_versions(carteira_id, created_at DESC)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_negocial_fechamento_period ON negocial.fechamento_mensal(ano DESC, mes DESC, carteira)")

    op.execute("ALTER TABLE negocial.users DROP CONSTRAINT IF EXISTS negocial_users_carteira_check")
    op.execute("ALTER TABLE negocial.users ADD CONSTRAINT negocial_users_carteira_check CHECK (carteira IS NULL OR btrim(carteira) <> '')")
    op.execute("ALTER TABLE negocial.users DROP CONSTRAINT IF EXISTS negocial_users_role_check")
    op.execute("ALTER TABLE negocial.users ADD CONSTRAINT negocial_users_role_check CHECK (role IN ('ADMIN', 'USER', 'admin', 'user'))")
    op.execute("ALTER TABLE negocial.pareceres DROP CONSTRAINT IF EXISTS negocial_pareceres_carteira_check")
    op.execute("ALTER TABLE negocial.pareceres ADD CONSTRAINT negocial_pareceres_carteira_check CHECK (btrim(carteira) <> '')")
    op.execute("ALTER TABLE negocial.pareceres DROP CONSTRAINT IF EXISTS negocial_pareceres_motivo_check")

    op.execute(
        """
        INSERT INTO negocial.operational_versions (scope, version)
        VALUES ('producao', 1), ('pareceres', 1), ('carteiras', 1)
        ON CONFLICT (scope) DO NOTHING
        """
    )
    op.execute(
        """
        CREATE OR REPLACE VIEW negocial.producao_unificada AS
        SELECT
            pr.id,
            pr.data_acordo,
            COALESCE(it.debit_id, rt.suitid, gamma.npj, dyn.identificador, '') AS npj,
            it.cpf,
            pr.cliente,
            COALESCE(gamma.gecor, '') AS gecor,
            NULL::INTEGER AS dias_atraso,
            it.data_primeiro_atraso,
            it.portfolio,
            it.carteira_alpha,
            pr.valor_total_acordo,
            pr.valor_entrada,
            COALESCE(gamma.valor_ho, 0) AS valor_ho,
            COALESCE(gamma.percentual_ho, 0) AS percentual_ho,
            pr.tipo_acordo,
            pr.data_vencimento,
            pr.data_pagamento,
            pr.status,
            pr.justificativa_status,
            COALESCE(gamma.autorizacao_flexibilizacao, 'NAO') AS autorizacao_flexibilizacao,
            pr.carteira,
            pr.user_id,
            pr.created_at,
            pr.updated_at
        FROM negocial.producao_registros pr
        LEFT JOIN negocial.producao_gamma gamma ON gamma.producao_id = pr.id
        LEFT JOIN negocial.producao_alpha it ON it.producao_id = pr.id
        LEFT JOIN negocial.producao_beta rt ON rt.producao_id = pr.id
        LEFT JOIN LATERAL (
            SELECT pc.valor_texto AS identificador
            FROM negocial.producao_campos pc
            JOIN negocial.carteira_colunas cc ON cc.id = pc.coluna_id
            WHERE pc.producao_id = pr.id AND cc.identificador = TRUE
            ORDER BY cc.ordem, cc.id
            LIMIT 1
        ) dyn ON TRUE
        """
    )
    op.execute(
        """
        INSERT INTO negocial.schema_migrations_meta (revision, description)
        VALUES ('20260720_0011', 'Consolida estruturas operacionais no Alembic')
        ON CONFLICT (revision) DO NOTHING
        """
    )


def downgrade() -> None:
    # Estruturas compartilhadas e dados operacionais nao sao removidos para
    # evitar perda acidental. O downgrade apenas retira os indices desta etapa.
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return
    op.execute("DROP INDEX IF EXISTS negocial.ix_negocial_fechamento_period")
    op.execute("DROP INDEX IF EXISTS negocial.ix_negocial_schema_versions_wallet_date")
    op.execute("DROP INDEX IF EXISTS negocial.ix_negocial_correcoes_unread")
    op.execute("DROP INDEX IF EXISTS negocial.ix_negocial_correcoes_producao_date")
