"""Baseline do schema negocial em PostgreSQL.

Revision ID: 20260707_0001
Revises:
Create Date: 2026-07-07
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa

from backend.database import Base
import backend.models  # noqa: F401 - registers every mapped table in Base.metadata


revision = "20260707_0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return

    op.execute("CREATE SCHEMA IF NOT EXISTS negocial")

    # A baseline original apenas carimbava um banco que ja estava montado pelo
    # bootstrap. Criar as tabelas mapeadas aqui torna a cadeia reproduzivel em
    # bancos vazios sem voltar a executar DDL durante o startup da aplicacao.
    Base.metadata.create_all(bind=bind)

    # Estruturas operacionais usadas por revisions posteriores e que nao sao
    # entidades ORM da aplicacao negocial.
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS negocial.producao_gamma_gerencial (
            producao_id INTEGER PRIMARY KEY REFERENCES negocial.producao_registros(id) ON DELETE CASCADE,
            uf VARCHAR(2),
            data_ajuizamento DATE,
            updated_at TIMESTAMPTZ DEFAULT NOW()
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS negocial.producao_correcoes (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            producao_id INTEGER NOT NULL REFERENCES negocial.producao_registros(id) ON DELETE CASCADE,
            campo TEXT NOT NULL,
            valor_anterior TEXT,
            valor_novo TEXT,
            corrigido_por TEXT NOT NULL,
            motivo TEXT,
            criado_em TIMESTAMPTZ DEFAULT NOW(),
            visualizado_pelo_negociador BOOLEAN DEFAULT FALSE
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS negocial.carteira_schema_versions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            carteira_id INTEGER NOT NULL REFERENCES negocial.carteiras_negociais(id) ON DELETE CASCADE,
            version_number INTEGER NOT NULL,
            action VARCHAR(80) NOT NULL,
            schema_json JSONB NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            UNIQUE (carteira_id, version_number)
        )
        """
    )

    # Baseline: as tabelas ja existem em producao. Esta revision registra o
    # estado atual para que novas mudancas passem a ser feitas por migrations.
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS negocial.schema_migrations_meta (
            id SERIAL PRIMARY KEY,
            revision VARCHAR(80) NOT NULL UNIQUE,
            description TEXT NOT NULL,
            applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
        """
    )
    op.execute(
        """
        INSERT INTO negocial.schema_migrations_meta (revision, description)
        VALUES ('20260707_0001', 'Baseline apos migracao para producao_registros')
        ON CONFLICT (revision) DO NOTHING
        """
    )
    op.execute("DROP VIEW IF EXISTS negocial.producao_diaria_unificada")
    op.execute(
        """
        CREATE OR REPLACE VIEW negocial.producao_unificada AS
        SELECT
            pr.id,
            pr.data_acordo,
            COALESCE(it.debit_id, gamma.npj, '') AS npj,
            it.cpf,
            pr.cliente,
            COALESCE(gamma.gecor, '') AS gecor,
            NULL::INTEGER AS dias_atraso,
            it.data_primeiro_atraso,
            it.portfolio,
            it.carteira_alpha,
            pr.valor_total_acordo,
            pr.valor_entrada,
            COALESCE(gamma.valor_ho, 0) AS valor_ho,
            COALESCE(gamma.percentual_ho, 0) AS percentual_ho,
            pr.tipo_acordo,
            pr.data_vencimento,
            pr.data_pagamento,
            pr.status,
            pr.justificativa_status,
            COALESCE(gamma.autorizacao_flexibilizacao, 'NAO') AS autorizacao_flexibilizacao,
            pr.carteira,
            pr.user_id,
            pr.created_at,
            pr.updated_at
        FROM negocial.producao_registros pr
        LEFT JOIN negocial.producao_gamma gamma ON gamma.producao_id = pr.id
        LEFT JOIN negocial.producao_alpha it ON it.producao_id = pr.id
        """
    )


def downgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return
    op.execute("DELETE FROM negocial.schema_migrations_meta WHERE revision = '20260707_0001'")
