"""Metas trimestrais e honorarios excepcionais da Alpha.

Revision ID: 20260728_0018
Revises: 20260727_0017
Create Date: 2026-07-28
"""

from __future__ import annotations

from alembic import op


revision = "20260728_0018"
down_revision = "20260727_0017"
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS negocial.alpha_meta_imports (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            file_name VARCHAR(255) NOT NULL,
            file_sha256 VARCHAR(64) NOT NULL UNIQUE,
            source_path TEXT,
            quarter VARCHAR(8) NOT NULL,
            office VARCHAR(80) NOT NULL,
            status VARCHAR(20) NOT NULL DEFAULT 'RASCUNHO',
            raw_data_json JSONB NOT NULL,
            validation_json JSONB NOT NULL,
            created_by VARCHAR(80) NOT NULL,
            applied_by VARCHAR(80),
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            applied_at TIMESTAMPTZ,
            CONSTRAINT ck_alpha_meta_import_status
                CHECK (status IN ('RASCUNHO', 'VALIDADO', 'APLICADO', 'SUBSTITUIDO', 'ERRO'))
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS negocial.alpha_portfolio_goals (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            import_id BIGINT REFERENCES negocial.alpha_meta_imports(id) ON DELETE CASCADE,
            portfolio VARCHAR(180) NOT NULL,
            portfolio_key VARCHAR(180) NOT NULL,
            group_name VARCHAR(80) NOT NULL,
            competence DATE NOT NULL,
            meta_caixa NUMERIC(16, 2) NOT NULL DEFAULT 0,
            retomadas_count INTEGER NOT NULL DEFAULT 0,
            retomadas_value NUMERIC(16, 2) NOT NULL DEFAULT 0,
            meta_pnt NUMERIC(16, 2) NOT NULL DEFAULT 0,
            source_type VARCHAR(20) NOT NULL DEFAULT 'PDF',
            active BOOLEAN NOT NULL DEFAULT FALSE,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            CONSTRAINT uq_alpha_goal_import_portfolio_month
                UNIQUE (import_id, portfolio_key, competence),
            CONSTRAINT ck_alpha_goal_nonnegative
                CHECK (
                    meta_caixa >= 0 AND retomadas_count >= 0
                    AND retomadas_value >= 0 AND meta_pnt >= 0
                ),
            CONSTRAINT ck_alpha_goal_source
                CHECK (source_type IN ('PDF', 'MANUAL'))
        )
        """
    )
    op.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS uq_alpha_goal_active_portfolio_month
        ON negocial.alpha_portfolio_goals(portfolio_key, competence)
        WHERE active = TRUE
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS negocial.alpha_ho_rule_versions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR(120) NOT NULL,
            effective_from DATE NOT NULL,
            effective_to DATE,
            status VARCHAR(20) NOT NULL DEFAULT 'RASCUNHO',
            matrix_json JSONB NOT NULL,
            created_by VARCHAR(80) NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            activated_at TIMESTAMPTZ,
            CONSTRAINT ck_alpha_ho_rule_status
                CHECK (status IN ('RASCUNHO', 'ATIVA', 'ENCERRADA')),
            CONSTRAINT ck_alpha_ho_rule_dates
                CHECK (effective_to IS NULL OR effective_to >= effective_from)
        )
        """
    )
    op.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS uq_alpha_ho_rule_active_period
        ON negocial.alpha_ho_rule_versions(effective_from)
        WHERE status = 'ATIVA'
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS negocial.alpha_ho_calculations (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            producao_id INTEGER NOT NULL
                REFERENCES negocial.producao_registros(id) ON DELETE CASCADE,
            competence DATE NOT NULL,
            portfolio_key VARCHAR(180) NOT NULL,
            goal_id BIGINT
                REFERENCES negocial.alpha_portfolio_goals(id) ON DELETE SET NULL,
            rule_version_id BIGINT NOT NULL
                REFERENCES negocial.alpha_ho_rule_versions(id) ON DELETE RESTRICT,
            delay_days INTEGER NOT NULL,
            accumulated_production NUMERIC(18, 2) NOT NULL DEFAULT 0,
            attainment_percent NUMERIC(9, 4) NOT NULL DEFAULT 0,
            applied_rate NUMERIC(8, 4) NOT NULL,
            base_value NUMERIC(16, 2) NOT NULL,
            calculated_honorarios NUMERIC(16, 2) NOT NULL,
            calculation_mode VARCHAR(20) NOT NULL DEFAULT 'CONFERENCIA',
            details_json JSONB NOT NULL,
            calculated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            CONSTRAINT uq_alpha_ho_calculation_record_mode
                UNIQUE (producao_id, calculation_mode),
            CONSTRAINT ck_alpha_ho_calculation_values
                CHECK (
                    delay_days >= 0 AND accumulated_production >= 0
                    AND attainment_percent >= 0 AND applied_rate BETWEEN 0 AND 100
                    AND base_value >= 0 AND calculated_honorarios >= 0
                ),
            CONSTRAINT ck_alpha_ho_calculation_mode
                CHECK (calculation_mode IN ('CONFERENCIA', 'OFICIAL'))
        )
        """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_alpha_meta_import_quarter_status "
        "ON negocial.alpha_meta_imports(quarter, status)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_alpha_goal_competence_portfolio "
        "ON negocial.alpha_portfolio_goals(competence, portfolio_key)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_alpha_ho_calculation_competence_portfolio "
        "ON negocial.alpha_ho_calculations(competence, portfolio_key)"
    )
    bind.exec_driver_sql(
        """
        INSERT INTO negocial.alpha_ho_rule_versions (
            name, effective_from, status, matrix_json, created_by, activated_at
        )
        SELECT
            'Matriz padrao Alpha',
            DATE '2026-01-01',
            'ATIVA',
            '{
              "attainment_bands": [
                {"key":"BELOW_85","label":"Abaixo de 85","min":null,"max":85},
                {"key":"BETWEEN_85_110","label":"Entre 85 e 110","min":85,"max":110},
                {"key":"ABOVE_110","label":"Acima de 110","min":110,"max":null}
              ],
              "delay_bands": [
                {"min":1,"max":360,"rates":{"BELOW_85":8,"BETWEEN_85_110":10,"ABOVE_110":12}},
                {"min":361,"max":720,"rates":{"BELOW_85":13,"BETWEEN_85_110":15,"ABOVE_110":17}},
                {"min":721,"max":1080,"rates":{"BELOW_85":13,"BETWEEN_85_110":15,"ABOVE_110":17}},
                {"min":1081,"max":2400,"rates":{"BELOW_85":18,"BETWEEN_85_110":20,"ABOVE_110":22}},
                {"min":2401,"max":null,"rates":{"BELOW_85":23,"BETWEEN_85_110":25,"ABOVE_110":27}}
              ],
              "eligible_statuses": ["AGUARDANDO_PAGAMENTO","PAGAMENTO_REALIZADO","AGUARDANDO_LEVANTAMENTO"],
              "base_field": "VALOR_TOTAL",
              "portfolio_field": "PORTFOLIO",
              "first_delay_date_field": "DATA_DO_1_ATRASO"
            }'::jsonb,
            'migration',
            NOW()
        WHERE NOT EXISTS (
            SELECT 1 FROM negocial.alpha_ho_rule_versions WHERE status = 'ATIVA'
        )
        """
    )
    op.execute(
        """
        INSERT INTO negocial.schema_migrations_meta (revision, description)
        VALUES ('20260728_0018', 'Metas trimestrais e H.O excepcional da Alpha')
        ON CONFLICT (revision) DO NOTHING
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS negocial.alpha_ho_calculations")
    op.execute("DROP TABLE IF EXISTS negocial.alpha_ho_rule_versions")
    op.execute("DROP TABLE IF EXISTS negocial.alpha_portfolio_goals")
    op.execute("DROP TABLE IF EXISTS negocial.alpha_meta_imports")
