"""Alertas operacionais e indices de performance.

Revision ID: 20260720_0002
Revises: 20260720_0001
Create Date: 2026-07-20
"""
from __future__ import annotations

from alembic import op


revision = "20260720_0002"
down_revision = "20260720_0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""
        CREATE TABLE IF NOT EXISTS gerencial.database_alerts (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            fingerprint TEXT NOT NULL UNIQUE,
            alert_type TEXT NOT NULL,
            severity TEXT NOT NULL,
            message TEXT NOT NULL,
            source TEXT NOT NULL DEFAULT 'database_monitoring',
            status TEXT NOT NULL DEFAULT 'open',
            details_json JSONB NOT NULL DEFAULT '{}'::jsonb,
            first_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            occurrence_count INTEGER NOT NULL DEFAULT 1,
            acknowledged_by TEXT,
            acknowledged_at TIMESTAMPTZ,
            resolved_at TIMESTAMPTZ
        )
    """)
    op.execute("CREATE INDEX IF NOT EXISTS ix_gerencial_database_alerts_status_severity ON gerencial.database_alerts(status, severity, last_seen_at DESC)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_gerencial_database_alerts_type_date ON gerencial.database_alerts(alert_type, last_seen_at DESC)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_gerencial_events_negociador_date ON gerencial.events(negociador_id, changed_at DESC)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_gerencial_snapshots_negociador_date ON gerencial.snapshots(negociador_id, captured_at DESC)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_gerencial_overview_reads_user_event ON gerencial.overview_reads(usuario, event_id, change_index)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_gerencial_notification_reads_user_notification ON gerencial.notification_reads(usuario, notification_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_gerencial_protocolos_status_updated ON gerencial.protocolos(status, updated_at DESC)")


def downgrade() -> None:
    op.drop_table("database_alerts", schema="gerencial")
