"""Unifica o Colchao por carteira, acordo e parcela.

Revision ID: 20260814_0006
Revises: 20260811_0005
Create Date: 2026-08-14
"""
from alembic import op


revision = "20260814_0006"
down_revision = "20260811_0005"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS gerencial.colchao_acordos (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            carteira TEXT NOT NULL,
            source_sheet TEXT NOT NULL DEFAULT '',
            identifier TEXT NOT NULL,
            agreement_number TEXT NOT NULL,
            cliente TEXT,
            cpf_cnpj TEXT,
            operador TEXT,
            tipo_acordo TEXT,
            metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
            active BOOLEAN NOT NULL DEFAULT TRUE,
            source TEXT NOT NULL DEFAULT 'database',
            created_by TEXT,
            updated_by TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            UNIQUE (carteira, source_sheet, identifier, agreement_number)
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS gerencial.colchao_parcelas (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            acordo_id BIGINT NOT NULL REFERENCES gerencial.colchao_acordos(id) ON DELETE CASCADE,
            carteira TEXT NOT NULL,
            source_sheet TEXT NOT NULL DEFAULT '',
            source_row INTEGER NOT NULL,
            parcela TEXT,
            valor NUMERIC(14,2),
            vencimento TEXT,
            status TEXT NOT NULL DEFAULT 'A VENCER',
            observacao TEXT,
            bucket TEXT,
            raw_json JSONB NOT NULL DEFAULT '{}'::jsonb,
            active BOOLEAN NOT NULL DEFAULT TRUE,
            source_updated_at TIMESTAMPTZ,
            updated_by TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            UNIQUE (carteira, source_sheet, source_row)
        )
        """
    )
    op.execute("CREATE INDEX IF NOT EXISTS ix_colchao_acordos_carteira_active ON gerencial.colchao_acordos(carteira, active)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_colchao_acordos_identifier ON gerencial.colchao_acordos(carteira, identifier)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_colchao_parcelas_status ON gerencial.colchao_parcelas(carteira, active, status)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_colchao_parcelas_vencimento ON gerencial.colchao_parcelas(carteira, vencimento)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_colchao_parcelas_acordo ON gerencial.colchao_parcelas(acordo_id, active)")

    for legacy_table, carteira in (("colchao_alpha", "ALPHA"), ("colchao_beta", "BETA")):
        op.execute(
            f"""
            INSERT INTO gerencial.colchao_acordos (
                carteira, source_sheet, identifier, agreement_number, cliente, cpf_cnpj,
                operador, tipo_acordo, metadata_json, active, source, updated_by,
                created_at, updated_at
            )
            SELECT DISTINCT ON (
                COALESCE(NULLIF(BTRIM(sheet_name), ''), 'COLCHAO'),
                COALESCE(NULLIF(BTRIM(identifier), ''), '__ROW__' || row_number::text),
                COALESCE(NULLIF(BTRIM(acordo), ''), '1')
            )
                '{carteira}',
                COALESCE(NULLIF(BTRIM(sheet_name), ''), 'COLCHAO'),
                COALESCE(NULLIF(BTRIM(identifier), ''), '__ROW__' || row_number::text),
                COALESCE(NULLIF(BTRIM(acordo), ''), '1'),
                cliente, cpf_cnpj, operador,
                COALESCE(raw_json->>'TIPO DE ACORDO', raw_json->>'TIPO'),
                jsonb_build_object('legacy_table', '{legacy_table}'),
                active, 'legacy_migration', updated_by,
                COALESCE(created_at, NOW()), COALESCE(updated_at, NOW())
            FROM gerencial.{legacy_table}
            ORDER BY
                COALESCE(NULLIF(BTRIM(sheet_name), ''), 'COLCHAO'),
                COALESCE(NULLIF(BTRIM(identifier), ''), '__ROW__' || row_number::text),
                COALESCE(NULLIF(BTRIM(acordo), ''), '1'),
                updated_at DESC NULLS LAST
            ON CONFLICT (carteira, source_sheet, identifier, agreement_number)
            DO UPDATE SET
                cliente = EXCLUDED.cliente,
                cpf_cnpj = EXCLUDED.cpf_cnpj,
                operador = EXCLUDED.operador,
                tipo_acordo = EXCLUDED.tipo_acordo,
                active = EXCLUDED.active,
                updated_by = EXCLUDED.updated_by,
                updated_at = EXCLUDED.updated_at
            """
        )
        op.execute(
            f"""
            INSERT INTO gerencial.colchao_parcelas (
                acordo_id, carteira, source_sheet, source_row, parcela, valor, vencimento,
                status, observacao, bucket, raw_json, active, source_updated_at,
                updated_by, created_at, updated_at
            )
            SELECT
                a.id, '{carteira}', COALESCE(NULLIF(BTRIM(l.sheet_name), ''), 'COLCHAO'),
                l.row_number, l.parcela, l.valor, l.vencimento,
                COALESCE(NULLIF(BTRIM(l.status), ''), 'A VENCER'), l.observacao,
                l.bucket, l.raw_json, l.active, l.source_updated_at, l.updated_by,
                COALESCE(l.created_at, NOW()), COALESCE(l.updated_at, NOW())
            FROM gerencial.{legacy_table} l
            JOIN gerencial.colchao_acordos a
              ON a.carteira = '{carteira}'
             AND a.source_sheet = COALESCE(NULLIF(BTRIM(l.sheet_name), ''), 'COLCHAO')
             AND a.identifier = COALESCE(NULLIF(BTRIM(l.identifier), ''), '__ROW__' || l.row_number::text)
             AND a.agreement_number = COALESCE(NULLIF(BTRIM(l.acordo), ''), '1')
            ON CONFLICT (carteira, source_sheet, source_row)
            DO UPDATE SET
                acordo_id = EXCLUDED.acordo_id,
                parcela = EXCLUDED.parcela,
                valor = EXCLUDED.valor,
                vencimento = EXCLUDED.vencimento,
                status = EXCLUDED.status,
                observacao = EXCLUDED.observacao,
                bucket = EXCLUDED.bucket,
                raw_json = EXCLUDED.raw_json,
                active = EXCLUDED.active,
                source_updated_at = EXCLUDED.source_updated_at,
                updated_by = EXCLUDED.updated_by,
                updated_at = EXCLUDED.updated_at
            """
        )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS gerencial.colchao_parcelas")
    op.execute("DROP TABLE IF EXISTS gerencial.colchao_acordos")
