"""Baseline formal do schema gerencial.

Revision ID: 20260720_0001
Revises:
Create Date: 2026-07-20
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = "20260720_0001"
down_revision = None
branch_labels = None
depends_on = None


TABLE_STATEMENTS = (
    """CREATE TABLE IF NOT EXISTS gerencial.users (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        username TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL, salt TEXT NOT NULL,
        role TEXT NOT NULL DEFAULT 'user', active BOOLEAN NOT NULL DEFAULT TRUE,
        created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL
    )""",
    """CREATE TABLE IF NOT EXISTS gerencial.negociadores (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nome TEXT NOT NULL, carteira TEXT, arquivo_path TEXT NOT NULL, sheet TEXT NOT NULL,
        senha TEXT, source_type TEXT NOT NULL DEFAULT 'planilha', negocial_user_id BIGINT,
        negocial_username TEXT, meta_pagamento NUMERIC(12,2), active BOOLEAN NOT NULL DEFAULT TRUE,
        last_mtime TEXT, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL
    )""",
    """CREATE TABLE IF NOT EXISTS gerencial.carteiras (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nome TEXT NOT NULL UNIQUE, descricao TEXT, active BOOLEAN NOT NULL DEFAULT TRUE,
        created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL
    )""",
    """CREATE TABLE IF NOT EXISTS gerencial.snapshots (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        negociador_id BIGINT NOT NULL REFERENCES gerencial.negociadores(id), sheet TEXT NOT NULL,
        captured_at TIMESTAMPTZ NOT NULL, content_json JSONB NOT NULL
    )""",
    """CREATE TABLE IF NOT EXISTS gerencial.events (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        negociador_id BIGINT NOT NULL REFERENCES gerencial.negociadores(id),
        snapshot_before_id BIGINT REFERENCES gerencial.snapshots(id),
        snapshot_after_id BIGINT NOT NULL REFERENCES gerencial.snapshots(id),
        event_type TEXT NOT NULL, sheet TEXT NOT NULL, file_path TEXT NOT NULL,
        changed_at TIMESTAMPTZ NOT NULL, changes_count INTEGER NOT NULL,
        delta_json JSONB NOT NULL, metadata_json JSONB NOT NULL
    )""",
    """CREATE TABLE IF NOT EXISTS gerencial.overview_reads (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        event_id BIGINT NOT NULL REFERENCES gerencial.events(id), change_index INTEGER NOT NULL,
        usuario TEXT NOT NULL, read_at TIMESTAMPTZ NOT NULL,
        UNIQUE(event_id, change_index, usuario)
    )""",
    """CREATE TABLE IF NOT EXISTS gerencial.notification_reads (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        notification_id TEXT NOT NULL, usuario TEXT NOT NULL, read_at TIMESTAMPTZ NOT NULL,
        UNIQUE(notification_id, usuario)
    )""",
    """CREATE TABLE IF NOT EXISTS gerencial.notes (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        target_type TEXT NOT NULL, target_id TEXT NOT NULL, text TEXT NOT NULL,
        usuario TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL
    )""",
    """CREATE TABLE IF NOT EXISTS gerencial.sessions (
        token TEXT PRIMARY KEY, user_id BIGINT NOT NULL REFERENCES gerencial.users(id),
        created_at TIMESTAMPTZ NOT NULL, expires_at TIMESTAMPTZ NOT NULL
    )""",
    """CREATE TABLE IF NOT EXISTS gerencial.general_audit (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        actor TEXT, actor_role TEXT, action TEXT NOT NULL, entity_type TEXT NOT NULL,
        entity_id TEXT, entity_label TEXT, outcome TEXT NOT NULL DEFAULT 'success',
        details_json JSONB NOT NULL, ip_address TEXT, created_at TIMESTAMPTZ NOT NULL
    )""",
    """CREATE TABLE IF NOT EXISTS gerencial.role_permissions (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        role TEXT NOT NULL, permission TEXT NOT NULL, allowed BOOLEAN NOT NULL DEFAULT FALSE,
        updated_at TIMESTAMPTZ NOT NULL, UNIQUE(role, permission)
    )""",
    """CREATE TABLE IF NOT EXISTS gerencial.user_permissions (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id BIGINT NOT NULL REFERENCES gerencial.users(id) ON DELETE CASCADE,
        permission TEXT NOT NULL, allowed BOOLEAN NOT NULL DEFAULT FALSE,
        updated_at TIMESTAMPTZ NOT NULL, UNIQUE(user_id, permission)
    )""",
    """CREATE TABLE IF NOT EXISTS gerencial.protocolos (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        row_key INTEGER NOT NULL UNIQUE, data_mes TEXT, carteira TEXT, nome TEXT, pj TEXT,
        processo TEXT, data_solicitacao TEXT, status TEXT NOT NULL DEFAULT 'PENDENTE',
        data_conclusao TEXT, observacao TEXT, extra_json JSONB, source TEXT NOT NULL DEFAULT 'database',
        created_by TEXT, updated_by TEXT, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL
    )""",
    """CREATE TABLE IF NOT EXISTS gerencial.colchao_alpha (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        sheet_name TEXT NOT NULL, row_number INTEGER NOT NULL, identifier TEXT, cliente TEXT,
        cpf_cnpj TEXT, acordo TEXT, parcela TEXT, valor NUMERIC(14,2), vencimento TEXT,
        status TEXT, observacao TEXT, operador TEXT, bucket TEXT, raw_json JSONB NOT NULL,
        active BOOLEAN NOT NULL DEFAULT TRUE, source_updated_at TIMESTAMPTZ, updated_by TEXT,
        created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL,
        UNIQUE(sheet_name, row_number)
    )""",
    """CREATE TABLE IF NOT EXISTS gerencial.colchao_beta (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        sheet_name TEXT NOT NULL, row_number INTEGER NOT NULL, identifier TEXT, cliente TEXT,
        cpf_cnpj TEXT, acordo TEXT, parcela TEXT, valor NUMERIC(14,2), vencimento TEXT,
        status TEXT, observacao TEXT, operador TEXT, bucket TEXT, raw_json JSONB NOT NULL,
        active BOOLEAN NOT NULL DEFAULT TRUE, source_updated_at TIMESTAMPTZ, updated_by TEXT,
        created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL,
        UNIQUE(sheet_name, row_number)
    )""",
    """CREATE TABLE IF NOT EXISTS gerencial.db_retention_policies (
        scope TEXT PRIMARY KEY, retention_days INTEGER NOT NULL, keep_latest INTEGER NOT NULL DEFAULT 0,
        enabled BOOLEAN NOT NULL DEFAULT TRUE, updated_at TIMESTAMPTZ NOT NULL
    )""",
    """CREATE TABLE IF NOT EXISTS gerencial.data_quality_issues (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        schema_name TEXT NOT NULL, table_name TEXT NOT NULL, entity_id TEXT,
        issue_type TEXT NOT NULL, severity TEXT NOT NULL DEFAULT 'warning', details_json JSONB NOT NULL,
        resolved BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        resolved_at TIMESTAMPTZ
    )""",
    """CREATE TABLE IF NOT EXISTS gerencial.database_health_snapshots (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        captured_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), database_size_bytes BIGINT NOT NULL,
        max_connections INTEGER NOT NULL, total_connections INTEGER NOT NULL,
        active_connections INTEGER NOT NULL, idle_connections INTEGER NOT NULL,
        cache_hit_percent NUMERIC(7,2) NOT NULL, transactions_committed BIGINT NOT NULL,
        transactions_rolled_back BIGINT NOT NULL, deadlocks BIGINT NOT NULL, temp_bytes BIGINT NOT NULL,
        waiting_locks INTEGER NOT NULL, long_transactions INTEGER NOT NULL,
        slowest_transaction_seconds NUMERIC(12,2) NOT NULL,
        pool_stats_json JSONB NOT NULL DEFAULT '{}'::jsonb, alerts_json JSONB NOT NULL DEFAULT '[]'::jsonb
    )""",
    """CREATE TABLE IF NOT EXISTS gerencial.database_table_growth_snapshots (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        health_snapshot_id BIGINT NOT NULL REFERENCES gerencial.database_health_snapshots(id) ON DELETE CASCADE,
        schema_name TEXT NOT NULL, table_name TEXT NOT NULL, row_estimate BIGINT NOT NULL,
        dead_rows BIGINT NOT NULL, size_bytes BIGINT NOT NULL, growth_bytes BIGINT NOT NULL DEFAULT 0,
        growth_percent NUMERIC(12,2) NOT NULL DEFAULT 0, captured_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        UNIQUE(health_snapshot_id, schema_name, table_name)
    )""",
)

INDEX_STATEMENTS = (
    "CREATE INDEX IF NOT EXISTS ix_gerencial_negociadores_active ON gerencial.negociadores(active)",
    "CREATE INDEX IF NOT EXISTS ix_gerencial_carteiras_active ON gerencial.carteiras(active)",
    "CREATE INDEX IF NOT EXISTS ix_gerencial_snapshots_negociador_id ON gerencial.snapshots(negociador_id)",
    "CREATE INDEX IF NOT EXISTS ix_gerencial_events_negociador_id ON gerencial.events(negociador_id)",
    "CREATE INDEX IF NOT EXISTS ix_gerencial_events_changed_at ON gerencial.events(changed_at)",
    "CREATE INDEX IF NOT EXISTS ix_gerencial_events_type_date ON gerencial.events(event_type, changed_at DESC)",
    "CREATE INDEX IF NOT EXISTS ix_gerencial_events_sheet_date ON gerencial.events(sheet, changed_at DESC)",
    "CREATE INDEX IF NOT EXISTS ix_gerencial_overview_reads_usuario ON gerencial.overview_reads(usuario)",
    "CREATE INDEX IF NOT EXISTS ix_gerencial_notification_reads_usuario ON gerencial.notification_reads(usuario)",
    "CREATE INDEX IF NOT EXISTS ix_gerencial_notes_target ON gerencial.notes(target_type, target_id)",
    "CREATE INDEX IF NOT EXISTS ix_gerencial_sessions_expires_at ON gerencial.sessions(expires_at)",
    "CREATE INDEX IF NOT EXISTS ix_gerencial_general_audit_created_at ON gerencial.general_audit(created_at)",
    "CREATE INDEX IF NOT EXISTS ix_gerencial_general_audit_action ON gerencial.general_audit(action)",
    "CREATE INDEX IF NOT EXISTS ix_gerencial_general_audit_actor ON gerencial.general_audit(actor)",
    "CREATE INDEX IF NOT EXISTS ix_gerencial_protocolos_status ON gerencial.protocolos(status)",
    "CREATE INDEX IF NOT EXISTS ix_gerencial_protocolos_carteira ON gerencial.protocolos(carteira)",
    "CREATE INDEX IF NOT EXISTS ix_gerencial_protocolos_updated_at ON gerencial.protocolos(updated_at)",
    "CREATE INDEX IF NOT EXISTS ix_gerencial_protocolos_carteira_status ON gerencial.protocolos(carteira, status)",
    "CREATE INDEX IF NOT EXISTS ix_gerencial_colchao_alpha_status ON gerencial.colchao_alpha(status)",
    "CREATE INDEX IF NOT EXISTS ix_gerencial_colchao_alpha_identifier ON gerencial.colchao_alpha(identifier)",
    "CREATE INDEX IF NOT EXISTS ix_gerencial_colchao_alpha_active_status ON gerencial.colchao_alpha(active, status)",
    "CREATE INDEX IF NOT EXISTS ix_gerencial_colchao_beta_status ON gerencial.colchao_beta(status)",
    "CREATE INDEX IF NOT EXISTS ix_gerencial_colchao_beta_identifier ON gerencial.colchao_beta(identifier)",
    "CREATE INDEX IF NOT EXISTS ix_gerencial_colchao_beta_active_status ON gerencial.colchao_beta(active, status)",
    "CREATE INDEX IF NOT EXISTS ix_gerencial_data_quality_open ON gerencial.data_quality_issues(resolved, severity, created_at DESC)",
    "CREATE INDEX IF NOT EXISTS ix_gerencial_data_quality_entity ON gerencial.data_quality_issues(schema_name, table_name, entity_id)",
    "CREATE INDEX IF NOT EXISTS ix_gerencial_database_health_captured ON gerencial.database_health_snapshots(captured_at DESC)",
    "CREATE INDEX IF NOT EXISTS ix_gerencial_database_growth_table_date ON gerencial.database_table_growth_snapshots(schema_name, table_name, captured_at DESC)",
)


def _constraint_exists(name: str) -> bool:
    return bool(op.get_bind().execute(sa.text("SELECT 1 FROM pg_constraint WHERE conname = :name"), {"name": name}).first())


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS gerencial")
    for statement in TABLE_STATEMENTS:
        op.execute(statement)
    for statement in INDEX_STATEMENTS:
        op.execute(statement)
    constraints = (
        ("protocolos", "ck_gerencial_protocolos_status", "status IN ('PENDENTE', 'CONCLUIDO')"),
        ("events", "ck_gerencial_events_changes_count_non_negative", "changes_count >= 0"),
        ("negociadores", "ck_gerencial_negociadores_source_type", "source_type IN ('planilha', 'sistema')"),
        ("negociadores", "gerencial_negociadores_carteira_check", "carteira IS NULL OR btrim(carteira) <> ''"),
        ("users", "gerencial_users_role_check", "lower(role) IN ('admin', 'gerencial', 'supervisor', 'user')"),
    )
    for table, name, expression in constraints:
        if not _constraint_exists(name):
            op.create_check_constraint(name, table, expression, schema="gerencial")


def downgrade() -> None:
    raise RuntimeError("O baseline gerencial nao possui downgrade destrutivo automatico.")
