"""Versiona a configuracao do Colchao por carteira.

Revision ID: 20260814_0007
Revises: 20260814_0006
Create Date: 2026-08-14
"""
from alembic import op


revision = "20260814_0007"
down_revision = "20260814_0006"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS gerencial.colchao_configuracoes (
            carteira TEXT PRIMARY KEY,
            version INTEGER NOT NULL DEFAULT 1,
            config_json JSONB NOT NULL DEFAULT '{}'::jsonb,
            updated_by TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS gerencial.colchao_configuracao_versions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            carteira TEXT NOT NULL,
            version INTEGER NOT NULL,
            config_json JSONB NOT NULL,
            created_by TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            UNIQUE (carteira, version)
        )
        """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_colchao_config_versions_carteira "
        "ON gerencial.colchao_configuracao_versions(carteira, version DESC)"
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS gerencial.colchao_configuracao_versions")
    op.execute("DROP TABLE IF EXISTS gerencial.colchao_configuracoes")
