-- PostgreSQL schema for Projeto Negocial
-- Target: one PostgreSQL database with two logical schemas:
--   gerencial: Aplicacao Gerencial
--   negocial: Aplicacao Negocial
--
-- Suggested database name: projeto_negocial
-- Run with a PostgreSQL user that can create schemas and tables.

BEGIN;

CREATE SCHEMA IF NOT EXISTS negocial;
CREATE SCHEMA IF NOT EXISTS gerencial;

-- ============================================================================
-- NEGOCIAL
-- ============================================================================

CREATE TABLE IF NOT EXISTS negocial.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(80) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'USER',
    active BOOLEAN NOT NULL DEFAULT TRUE,
    carteira VARCHAR(40),
    meta_pagamento NUMERIC(12, 2) NOT NULL DEFAULT 70000.00,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT negocial_users_role_check CHECK (role IN ('ADMIN', 'USER', 'admin', 'user')),
    CONSTRAINT negocial_users_carteira_check CHECK (
        carteira IS NULL OR carteira IN ('GAMMA', 'ALPHA', 'BETA')
    )
);

CREATE INDEX IF NOT EXISTS ix_negocial_users_id ON negocial.users (id);
CREATE UNIQUE INDEX IF NOT EXISTS ix_negocial_users_username ON negocial.users (username);

CREATE TABLE IF NOT EXISTS negocial.sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES negocial.users(id),
    token VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS ix_negocial_sessions_id ON negocial.sessions (id);
CREATE UNIQUE INDEX IF NOT EXISTS ix_negocial_sessions_token ON negocial.sessions (token);
CREATE INDEX IF NOT EXISTS ix_negocial_sessions_user_id ON negocial.sessions (user_id);

CREATE TABLE IF NOT EXISTS negocial.producao_registros (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_acordo DATE NOT NULL,
    cliente VARCHAR(180) NOT NULL,
    valor_total_acordo NUMERIC(14, 2) NOT NULL,
    valor_entrada NUMERIC(14, 2) NOT NULL,
    tipo_acordo VARCHAR(20) NOT NULL,
    data_vencimento DATE NOT NULL,
    data_pagamento DATE,
    status VARCHAR(40) NOT NULL,
    justificativa_status VARCHAR(600),
    autorizacao_flexibilizacao VARCHAR(80) NOT NULL DEFAULT 'NAO',
    carteira VARCHAR(40) NOT NULL,
    user_id BIGINT NOT NULL REFERENCES negocial.users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_negocial_producao_registros_status CHECK (
        status IN (
            'AGUARDANDO_PAGAMENTO',
            'PAGAMENTO_REALIZADO',
            'PROPOSTA',
            'PROPOSTA_NEGADA',
            'QUEBRA'
        )
    ),
    CONSTRAINT negocial_producao_tipo_acordo_check CHECK (tipo_acordo IN ('A_VISTA', 'PARCELADO'))
);

CREATE INDEX IF NOT EXISTS ix_negocial_producao_registros_cliente ON negocial.producao_registros (cliente);
CREATE INDEX IF NOT EXISTS ix_negocial_producao_registros_status ON negocial.producao_registros (status);
CREATE INDEX IF NOT EXISTS ix_negocial_producao_registros_carteira ON negocial.producao_registros (carteira);
CREATE INDEX IF NOT EXISTS ix_negocial_producao_registros_user_id ON negocial.producao_registros (user_id);
CREATE INDEX IF NOT EXISTS ix_negocial_producao_registros_data_acordo ON negocial.producao_registros (data_acordo);
CREATE INDEX IF NOT EXISTS ix_negocial_producao_registros_carteira_data ON negocial.producao_registros (carteira, data_acordo);
CREATE INDEX IF NOT EXISTS ix_negocial_producao_registros_user_data ON negocial.producao_registros (user_id, data_acordo);

CREATE TABLE IF NOT EXISTS negocial.producao_gamma (
    producao_id BIGINT PRIMARY KEY REFERENCES negocial.producao_registros(id) ON DELETE CASCADE,
    npj VARCHAR(80) NOT NULL,
    gecor VARCHAR(80) NOT NULL,
    valor_ho NUMERIC(14, 2) NOT NULL,
    percentual_ho NUMERIC(7, 2) NOT NULL,
    autorizacao_flexibilizacao VARCHAR(80) NOT NULL DEFAULT 'NAO'
);

CREATE INDEX IF NOT EXISTS ix_negocial_producao_gamma_npj ON negocial.producao_gamma (npj);

CREATE TABLE IF NOT EXISTS negocial.producao_alpha (
    producao_id BIGINT PRIMARY KEY REFERENCES negocial.producao_registros(id) ON DELETE CASCADE,
    debit_id VARCHAR(80) NOT NULL,
    cpf VARCHAR(14) NOT NULL,
    data_primeiro_atraso DATE NOT NULL,
    portfolio VARCHAR(120),
    carteira_alpha VARCHAR(20) NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_negocial_producao_alpha_debit_id ON negocial.producao_alpha (debit_id);
CREATE INDEX IF NOT EXISTS ix_negocial_producao_alpha_cpf ON negocial.producao_alpha (cpf);

CREATE TABLE IF NOT EXISTS negocial.producao_beta (
    producao_id BIGINT PRIMARY KEY REFERENCES negocial.producao_registros(id) ON DELETE CASCADE,
    suitid VARCHAR(80) NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_negocial_producao_beta_suitid ON negocial.producao_beta (suitid);

CREATE TABLE IF NOT EXISTS negocial.carteiras_negociais (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(80) NOT NULL UNIQUE,
    slug VARCHAR(80) NOT NULL UNIQUE,
    descricao VARCHAR(240),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS negocial.carteira_colunas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    carteira_id BIGINT NOT NULL REFERENCES negocial.carteiras_negociais(id) ON DELETE CASCADE,
    nome VARCHAR(120) NOT NULL,
    chave VARCHAR(120) NOT NULL,
    tipo VARCHAR(20) NOT NULL DEFAULT 'texto',
    obrigatoria BOOLEAN NOT NULL DEFAULT FALSE,
    identificador BOOLEAN NOT NULL DEFAULT FALSE,
    visivel BOOLEAN NOT NULL DEFAULT TRUE,
    ordem INTEGER NOT NULL DEFAULT 0,
    opcoes_json TEXT,
    UNIQUE (carteira_id, chave),
    CONSTRAINT ck_negocial_carteira_colunas_tipo CHECK (tipo IN ('texto', 'numero', 'moeda', 'data', 'select', 'boolean'))
);

CREATE TABLE IF NOT EXISTS negocial.producao_campos (
    producao_id BIGINT NOT NULL REFERENCES negocial.producao_registros(id) ON DELETE CASCADE,
    coluna_id BIGINT NOT NULL REFERENCES negocial.carteira_colunas(id) ON DELETE CASCADE,
    valor_texto TEXT,
    valor_numero NUMERIC(18, 4),
    valor_data DATE,
    valor_json JSONB,
    updated_at TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY (producao_id, coluna_id)
);

CREATE INDEX IF NOT EXISTS ix_negocial_producao_campos_coluna_texto ON negocial.producao_campos (coluna_id, valor_texto);
CREATE INDEX IF NOT EXISTS ix_negocial_producao_campos_valor_data ON negocial.producao_campos (valor_data);

CREATE TABLE IF NOT EXISTS negocial.pareceres (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_solicitacao DATE NOT NULL,
    data_conclusao DATE,
    npj VARCHAR(80) NOT NULL,
    cliente VARCHAR(180) NOT NULL,
    motivo VARCHAR(120) NOT NULL,
    descricao VARCHAR(1000) NOT NULL,
    status VARCHAR(40) NOT NULL,
    carteira VARCHAR(40) NOT NULL,
    user_id BIGINT NOT NULL REFERENCES negocial.users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT negocial_pareceres_carteira_check CHECK (carteira IN ('GAMMA', 'ALPHA', 'BETA')),
    CONSTRAINT negocial_pareceres_status_check CHECK (status IN ('PENDENTE', 'SOLICITADO', 'CANCELADO')),
    CONSTRAINT negocial_pareceres_motivo_check CHECK (motivo IN ('PISO NEGOCIAL', 'PARECER', 'REUNIAO'))
);

CREATE INDEX IF NOT EXISTS ix_negocial_pareceres_id ON negocial.pareceres (id);
CREATE INDEX IF NOT EXISTS ix_negocial_pareceres_npj ON negocial.pareceres (npj);
CREATE INDEX IF NOT EXISTS ix_negocial_pareceres_cliente ON negocial.pareceres (cliente);
CREATE INDEX IF NOT EXISTS ix_negocial_pareceres_motivo ON negocial.pareceres (motivo);
CREATE INDEX IF NOT EXISTS ix_negocial_pareceres_status ON negocial.pareceres (status);
CREATE INDEX IF NOT EXISTS ix_negocial_pareceres_carteira ON negocial.pareceres (carteira);
CREATE INDEX IF NOT EXISTS ix_negocial_pareceres_user_id ON negocial.pareceres (user_id);
CREATE INDEX IF NOT EXISTS ix_negocial_pareceres_data_solicitacao ON negocial.pareceres (data_solicitacao);

-- ============================================================================
-- GERENCIAL
-- ============================================================================

CREATE TABLE IF NOT EXISTS gerencial.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    salt TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'user',
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT gerencial_users_role_check CHECK (lower(role) IN ('admin', 'gerencial', 'supervisor', 'user'))
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_gerencial_users_username ON gerencial.users (username);

CREATE TABLE IF NOT EXISTS gerencial.sessions (
    token TEXT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES gerencial.users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_gerencial_sessions_user_id ON gerencial.sessions (user_id);

CREATE TABLE IF NOT EXISTS gerencial.negociadores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    carteira TEXT,
    arquivo_path TEXT NOT NULL,
    sheet TEXT NOT NULL,
    senha TEXT,
    source_type TEXT NOT NULL DEFAULT 'planilha',
    negocial_user_id BIGINT REFERENCES negocial.users(id),
    negocial_username TEXT,
    meta_pagamento NUMERIC(12, 2),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    last_mtime DOUBLE PRECISION,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT gerencial_negociadores_source_type_check CHECK (source_type IN ('planilha', 'sistema')),
    CONSTRAINT gerencial_negociadores_carteira_check CHECK (
        carteira IS NULL OR carteira IN ('GAMMA', 'ALPHA', 'BETA')
    )
);

CREATE INDEX IF NOT EXISTS ix_gerencial_negociadores_nome ON gerencial.negociadores (nome);
CREATE INDEX IF NOT EXISTS ix_gerencial_negociadores_carteira ON gerencial.negociadores (carteira);
CREATE INDEX IF NOT EXISTS ix_gerencial_negociadores_active ON gerencial.negociadores (active);
CREATE INDEX IF NOT EXISTS ix_gerencial_negociadores_source_type ON gerencial.negociadores (source_type);
CREATE INDEX IF NOT EXISTS ix_gerencial_negociadores_negocial_user_id ON gerencial.negociadores (negocial_user_id);

CREATE TABLE IF NOT EXISTS gerencial.snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    negociador_id BIGINT NOT NULL REFERENCES gerencial.negociadores(id),
    sheet TEXT NOT NULL,
    captured_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    content_json JSONB NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_gerencial_snapshots_negociador_id ON gerencial.snapshots (negociador_id);
CREATE INDEX IF NOT EXISTS ix_gerencial_snapshots_captured_at ON gerencial.snapshots (captured_at);
CREATE INDEX IF NOT EXISTS ix_gerencial_snapshots_sheet ON gerencial.snapshots (sheet);

CREATE TABLE IF NOT EXISTS gerencial.events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    negociador_id BIGINT NOT NULL REFERENCES gerencial.negociadores(id),
    snapshot_before_id BIGINT REFERENCES gerencial.snapshots(id),
    snapshot_after_id BIGINT NOT NULL REFERENCES gerencial.snapshots(id),
    event_type TEXT NOT NULL,
    sheet TEXT NOT NULL,
    file_path TEXT NOT NULL,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    changes_count INTEGER NOT NULL,
    delta_json JSONB NOT NULL,
    metadata_json JSONB NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_gerencial_events_negociador_id ON gerencial.events (negociador_id);
CREATE INDEX IF NOT EXISTS ix_gerencial_events_changed_at ON gerencial.events (changed_at);
CREATE INDEX IF NOT EXISTS ix_gerencial_events_event_type ON gerencial.events (event_type);
CREATE INDEX IF NOT EXISTS ix_gerencial_events_sheet ON gerencial.events (sheet);
CREATE INDEX IF NOT EXISTS ix_gerencial_events_snapshot_after_id ON gerencial.events (snapshot_after_id);

CREATE TABLE IF NOT EXISTS gerencial.overview_reads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES gerencial.events(id),
    change_index INTEGER NOT NULL,
    usuario TEXT NOT NULL,
    read_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT gerencial_overview_reads_unique UNIQUE (event_id, change_index, usuario)
);

CREATE INDEX IF NOT EXISTS ix_gerencial_overview_reads_event_id ON gerencial.overview_reads (event_id);
CREATE INDEX IF NOT EXISTS ix_gerencial_overview_reads_usuario ON gerencial.overview_reads (usuario);

CREATE TABLE IF NOT EXISTS gerencial.notification_reads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_id TEXT NOT NULL,
    usuario TEXT NOT NULL,
    read_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT gerencial_notification_reads_unique UNIQUE (notification_id, usuario)
);

CREATE INDEX IF NOT EXISTS ix_gerencial_notification_reads_usuario ON gerencial.notification_reads (usuario);

CREATE TABLE IF NOT EXISTS gerencial.notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type TEXT NOT NULL,
    target_id TEXT NOT NULL,
    text TEXT NOT NULL,
    usuario TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_gerencial_notes_target ON gerencial.notes (target_type, target_id);
CREATE INDEX IF NOT EXISTS ix_gerencial_notes_usuario ON gerencial.notes (usuario);

COMMIT;
