export const state = {
  user: null,
  negociadores: [],
  carteiras: [],
  activeId: null,
  data: null,
  events: [],
  allEvents: [],
  sort: { column: null, dir: 1 },
  filters: {},
  overview: [],
  overviewVersion: "",
  overviewVersionKey: "",
  overviewRefreshTimer: null,
  monitorPlanilha: { data: null, sort: { column: null, dir: 1 }, filters: {} },
  configUsers: { gerencial: [], negociadores: [] },
  configPermissions: { permissions: {}, roles: {} },
  configUserPermissions: { permissions: {}, users: [] },
  configDiagnostic: null,
  analytics: { page: "executive", data: null, loading: false, requestId: 0 },
  defasagem: { page: "dashboard", data: null, loading: false, requestId: 0, recordPage: 1, recordPages: 1 },
  hub: { overview: [], pareceres: [], protocolos: [], ferramentas: [], errors: {} },
  hubVersion: "",
  notifications: [],
  notificationsVersion: "",
  notificationAlertsEnabled: false,
  activeGroup: "backoffice",
  dynamicToolId: null,
  configPage: "usuarios",
  overviewStatus: "unread",
  timeline: { selectedMonth: null, selectedDay: null, expandedHour: null, activeItem: null, activityType: "all", activitySearch: "", sheetVisible: false, sheetSnapshot: null, sheetSort: { column: null, dir: 1 }, sheetSearch: "", sheetCache: new Map(), months: [], version: "", totalChanges: 0 },
  negociadorProfile: { tab: "producao", corrections: [], month: null, year: null },
  carteira: { selected: null, query: "", adminItems: [], monitorTab: "timeline", workspaceTab: "overview" },
  mode: "mainhub",
  editing: null,
  parecer: {
    page: "dashboard",
    config: null,
    records: [],
    clients: [],
    pendentes: [],
    aprovacao: [],
    aprovacaoHistorico: [],
    aprovacaoTodos: [],
    approvalTab: "pendentes",
    sort: { column: null, dir: 1 },
    pageIndex: 1,
    pageSize: 50,
    autoTimer: null,
    syncTimer: null,
  },
  protocolo: {
    page: "dashboard",
    config: null,
    records: [],
  },
  colchao: {
    profile: null,
    profileSummaries: {},
    page: "dashboard",
    config: null,
    sheet: "",
    records: [],
    pendencias: [],
    dashboard: null,
    sort: { column: null, dir: 1 },
    completo: { page: 1, pageSize: 100, total: 0, totalPages: 1 },
    pendingStatusChanges: {},
      cache: { dashboard: null, records: {}, pendencias: null, clients: null, validation: null },
  },
};
